owner: aifie-inc
repo: saiteki-upptime

sites:
  - name: smartlp.site
    url: https://lp.smartlp.site
  - name: saiteki.site
    url: https://lp.saiteki.site

status-website:
  baseUrl: /saiteki-upptime
  name: upptime
